# Generated by Django 4.0.4 on 2022-05-11 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codename', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
                ('first_name', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('change_message', models.TextField()),
                ('action_flag', models.PositiveSmallIntegerField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoPlotlyDashDashapp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instance_name', models.CharField(max_length=100, unique=True)),
                ('slug', models.CharField(max_length=110, unique=True)),
                ('base_state', models.TextField()),
                ('creation', models.DateTimeField()),
                ('update', models.DateTimeField()),
                ('save_on_change', models.BooleanField()),
            ],
            options={
                'db_table': 'django_plotly_dash_dashapp',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoPlotlyDashStatelessapp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(max_length=100, unique=True)),
                ('slug', models.CharField(max_length=110, unique=True)),
            ],
            options={
                'db_table': 'django_plotly_dash_statelessapp',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GraphData',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('MSSubClass', models.CharField(blank=True, max_length=25, null=True)),
                ('MSZoning', models.CharField(blank=True, max_length=25, null=True)),
                ('LotFrontage', models.CharField(blank=True, max_length=25, null=True)),
                ('LotArea', models.CharField(blank=True, max_length=25, null=True)),
                ('Street', models.CharField(blank=True, max_length=25, null=True)),
                ('Alley', models.CharField(blank=True, max_length=25, null=True)),
                ('LotShape', models.CharField(blank=True, max_length=25, null=True)),
                ('LandContour', models.CharField(blank=True, max_length=25, null=True)),
                ('Utilities', models.CharField(blank=True, max_length=25, null=True)),
                ('LotConfig', models.CharField(blank=True, max_length=25, null=True)),
                ('LandSlope', models.CharField(blank=True, max_length=25, null=True)),
                ('Neighborhood', models.CharField(blank=True, max_length=25, null=True)),
                ('Condition1', models.CharField(blank=True, max_length=25, null=True)),
                ('Condition2', models.CharField(blank=True, max_length=25, null=True)),
                ('BldgType', models.CharField(blank=True, max_length=25, null=True)),
                ('HouseStyle', models.CharField(blank=True, max_length=25, null=True)),
                ('OverallQual', models.CharField(blank=True, max_length=25, null=True)),
                ('OverallCond', models.CharField(blank=True, max_length=25, null=True)),
                ('YearBuilt', models.CharField(blank=True, max_length=25, null=True)),
                ('YearRemodAdd', models.CharField(blank=True, max_length=25, null=True)),
                ('RoofStyle', models.CharField(blank=True, max_length=25, null=True)),
                ('RoofMatl', models.CharField(blank=True, max_length=25, null=True)),
                ('Exterior1st', models.CharField(blank=True, max_length=25, null=True)),
                ('Exterior2nd', models.CharField(blank=True, max_length=25, null=True)),
                ('MasVnrType', models.CharField(blank=True, max_length=25, null=True)),
                ('MasVnrArea', models.CharField(blank=True, max_length=25, null=True)),
                ('ExterQual', models.CharField(blank=True, max_length=25, null=True)),
                ('ExterCond', models.CharField(blank=True, max_length=25, null=True)),
                ('Foundation', models.CharField(blank=True, max_length=25, null=True)),
                ('BsmtQual', models.CharField(blank=True, max_length=25, null=True)),
                ('BsmtCond', models.CharField(blank=True, max_length=25, null=True)),
                ('BsmtExposure', models.CharField(blank=True, max_length=25, null=True)),
                ('BsmtFinType1', models.CharField(blank=True, max_length=25, null=True)),
                ('BsmtFinSF1', models.CharField(blank=True, max_length=25, null=True)),
                ('BsmtFinType2', models.CharField(blank=True, max_length=25, null=True)),
                ('BsmtFinSF2', models.CharField(blank=True, max_length=25, null=True)),
                ('BsmtUnfSF', models.CharField(blank=True, max_length=25, null=True)),
                ('TotalBsmtSF', models.CharField(blank=True, max_length=25, null=True)),
                ('Heating', models.CharField(blank=True, max_length=25, null=True)),
                ('HeatingQC', models.CharField(blank=True, max_length=25, null=True)),
                ('CentralAir', models.CharField(blank=True, max_length=25, null=True)),
                ('Electrical', models.CharField(blank=True, max_length=25, null=True)),
                ('SalePrice', models.CharField(blank=True, max_length=25, null=True)),
            ],
            options={
                'db_table': 'GraphData',
                'managed': False,
            },
        ),
    ]
